### ISSUE TITLE
Cringe detected

### ISSUE THREAD

**Issue by LonelyTrouvere** [TymofiiPys/OOP-Lab4-Pysarenkov#1]
Class components are cringe, rewrite in function components

**Comment by TymofiiPys** [comment]
Name one class component in frontend, I can't find any, bruh. Hope you aren't calling Java classes class components, as that would be a total brainrot.

**Comment by LonelyTrouvere** [comment]
Menu.js

**Comment by TymofiiPys** [comment]
Oy vey, I did forget to push a lot of trash into the repo, thanks! 
![зображення_2024-04-25_132031570](https://github.com/TymofiiPys/OOP-Lab4-Pysarenkov/assets/71066289/b3369634-245e-4ff7-8fdf-ddc03895c0f7)
